version: 0.1

phase:
  install:
    commands: 
      - echo installing nodejs
      - sudo apt install nodejs
      - sudo apt install npm
      - npm install

  build:
    commands:
      - echo Build started on 'date'
      - npm run build
      
artifacts:
  files:
    - '**/*'
  base-directory: 'public' 