version: '3.8'

services:
  nodejs:
    container_name: nodejs_chat_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "12345:12345"
    volumes:
      - ./public:/app/public
